---
title: "Vignette 1: Getting started"
---

---

# 1.1 What is `QDECR`?

`QDECR` is a tool that can be used to perform surface-based vertex-wise analyses in `R`. 

---

# 1.2 Requirements

In order to run `QDECR` you need to have several things ready:

* A Unix system.
* [Freesurfer](https://surfer.nmr.mgh.harvard.edu/) installed.
* Your images processed through Freesurfer with the `-qcache` flag.
* [`R`](https://www.r-project.org) installed.
* A lot of other `R` packages that will be installed automatically.
* [`Magick++`](https://www.imagemagick.org/Magick++/STL.html)

To install Freesurfer, [follow this tutorial](https://stackoverflow.com/questions/32530340/freesurfer-installed-on-ubuntu), but change the `wget` command to the most up-to-date version of Freesurfer (*the tutorial downloads Freesurfer 5.3.0 which is NOT the newest version*).

To install R on Ubuntu 18.04, [follow this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-r-on-ubuntu-18-04) and [run step 1 of this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-r-packages-using-devtools-on-ubuntu-18-04).

`Magick` Can easily be installed. Instructions can be found [here](https://cran.r-project.org/web/packages/magick/vignettes/intro.html#build_from_source).

Another error may pop up down the line. Try opening `freeview` on the command line:
```{bash eval = FALSE, tidy = FALSE}
slamballais@scs:~$ freeview
freeview.bin:  error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory.
```

For Ubuntu 16.10 and higher this is a problem, as `libpng12.so.0` does not support those. There is an easy workaround:
```{bash eval = FALSE, tidy = FALSE}
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```

For the sake of the vignette we will assume that you have done all these.

In R you first need to install the QDECR package:
```{r eval = FALSE, tidy = FALSE}
# Install the devtools package
if (!requireNamespace("devtools"))
  install.packages('devtools')

# Download and install QDECR from Github
devtools::install_github("slamballais/QDECR")

# Attach the package
library(QDECR)

```

And that's it. You are ready to use `QDECR`. 

---

# 1.3 Setting your parameters

UNDER CONSTRUCTION

---

[Next vignette: [2. Quick start](02-quick-start.html) or [3. Using `QDECR`](03-using-qdecr.html)]